export const SET_TIME = 'TIME/SET_TIME';
export const START_TIME = 'TIME/START_TIME';
export const STOP_TIME = 'TIME/STOP_TIME';
export const CHANGE_TIME = 'TIME/CHANGE_TIME';

export const CHANGE_POINTS_AKA = 'POINTS/CHANGE_POINTS_AKA';
export const CHANGE_POINTS_AO = 'POINTS/CHANGE_POINTS_AO';
export const SET_SENSHU = 'POINTS/SET_SENSHU';
export const RESET_POINTS = 'POINTS/RESET_POINTS';

export const CHANGE_WARNING = 'WARNINGS/CHANGE_WARNING'
export const RESET_WARNINGS = 'WARNINGS/RESET_WARNINGS'

export const SET_WINNER = 'WINNER/SET_WINNER';
export const RESET_WINNER = 'WINNER/RESET_WINNER';

export const SET_SCOREBOARD = 'SCOREBOARD/SET_SCOREBOARD';
export const SET_CONTROL_SCOREBOARD = 'SCOREBOARD/SET_CONTROL_SCOREBOARD';



